# Mask detection

## Importing libraries

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout, Flatten, Conv2D, MaxPooling2D
import pickle
print(tf.__version__)

2.12.0


## Getting the data from pickle file

In [2]:
x = pickle.load(open('x.pickle','rb'))
y = pickle.load(open('y.pickle','rb'))

### Normalizing the data 

In [3]:
x = x/255.0
print(x[0])

[[[0.52941176]
  [0.5254902 ]
  [0.5254902 ]
  ...
  [0.5254902 ]
  [0.6627451 ]
  [0.69019608]]

 [[0.50196078]
  [0.49803922]
  [0.49803922]
  ...
  [0.49019608]
  [0.63921569]
  [0.69803922]]

 [[0.4745098 ]
  [0.47058824]
  [0.47058824]
  ...
  [0.44705882]
  [0.6       ]
  [0.69411765]]

 ...

 [[0.70588235]
  [0.68235294]
  [0.65490196]
  ...
  [0.34117647]
  [0.35686275]
  [0.39215686]]

 [[0.69411765]
  [0.67058824]
  [0.63921569]
  ...
  [0.31764706]
  [0.3254902 ]
  [0.34117647]]

 [[0.68627451]
  [0.6627451 ]
  [0.63137255]
  ...
  [0.28627451]
  [0.30196078]
  [0.29411765]]]


## Making the model

In [4]:
model = Sequential([
    Conv2D(64, (3,3),input_shape = x.shape[1:]),
    Activation('relu'),
    MaxPooling2D(pool_size=(2,2)),

    Conv2D(64, (3,3)),
    Activation('relu'),
    MaxPooling2D(pool_size=(2,2)),

    Flatten(),
    Dense(64),

    Dense(1),
    Activation('sigmoid'),
])

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [5]:
model.fit(x, y, epochs=10, validation_split=0.1)

Epoch 1/10
282/282 [==============================] - 23s 77ms/step - loss: 0.2337 - accuracy: 0.8977 - val_loss: 0.1647 - val_accuracy: 0.9410
Epoch 2/10
282/282 [==============================] - 23s 82ms/step - loss: 0.0901 - accuracy: 0.9691 - val_loss: 0.0940 - val_accuracy: 0.9650
Epoch 3/10
282/282 [==============================] - 22s 78ms/step - loss: 0.0686 - accuracy: 0.9757 - val_loss: 0.0691 - val_accuracy: 0.9750
Epoch 4/10
282/282 [==============================] - 21s 75ms/step - loss: 0.0597 - accuracy: 0.9794 - val_loss: 0.1109 - val_accuracy: 0.9550
Epoch 5/10
282/282 [==============================] - 21s 74ms/step - loss: 0.0498 - accuracy: 0.9824 - val_loss: 0.0748 - val_accuracy: 0.9700
Epoch 6/10
282/282 [==============================] - 21s 73ms/step - loss: 0.0396 - accuracy: 0.9860 - val_loss: 0.0432 - val_accuracy: 0.9830
Epoch 7/10
282/282 [==============================] - 21s 73ms/step - loss: 0.0405 - accuracy: 0.9857 - val_loss: 0.0448 - val_accuracy:

## Saving a model

In [6]:
model.save('mask_detect')

INFO:tensorflow:Assets written to: mask_detect\assets


INFO:tensorflow:Assets written to: mask_detect\assets


## Loading a saved model

In [7]:
new_model = tf.keras.models.load_model('mask_detect')
new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 48, 48, 64)        640       
                                                                 
 activation (Activation)     (None, 48, 48, 64)        0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 24, 24, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 22, 22, 64)        36928     
                                                                 
 activation_1 (Activation)   (None, 22, 22, 64)        0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 11, 11, 64)       0         
 2D)                                                    